apiVersion: batch/v1
kind: CronJob
metadata:
  name: curl-every-minute
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: ping
              image: alpine/curl
              command: ["sh", "-ec", "curl -sS https://www.suse.com/"]
