apiVersion: v1
kind: Pod
metadata:
  name: mysql-vol
spec:
  containers:
    - name: mysql
      image: bitnami/mysql
      env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
      volumeMounts:
        - name: my-config
          mountPath: "/etc/foo"
          readOnly: true
  volumes:
    - name: my-config
      configMap:
        name: mysql
