apiVersion: v1
kind: Pod
metadata:
  name: mysql-secret
spec:
  containers:
    - name: mysql
      image: bitnami/mysql
      env:
        - name: MYSQL_REPLICATION_MODE
          valueFrom:
            configMapKeyRef:
              name: mysql
              key: replication-mode
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: replication-user